In [1]:
import numpy as np
import ot
import os

In [48]:
def extend(x,t_x, y, t_y, C):
    hat_x = np.zeros(len(x) + 1)
    hat_y = np.zeros(len(y) + 1)
    C_hat = np.zeros((C.shape[0] + 1, C.shape[1] + 1))
    C_hat[:len(x), :len(y)] = C
    hat_x[:len(x)] = x
    hat_x[len(x)] = np.sum(y)
    hat_y[len(y)] = np.sum(x)
    hat_y[:len(y)] = y
    C_hat[len(x), :len(y)] = t_y
    C_hat[:len(x), len(y)] = t_x
    return hat_x, hat_y, C_hat

In [67]:
l1 = np.array([255])
l2 = np.array([255, 255])
l3 = np.array([255, 255])
probs12 = np.array([[0.01, 0.95]])
probs23 = np.array([[0.90, 0.01], [0.01, 0.90]])

C12 = 1/probs12
C23 = 1/probs23
t1 = np.zeros(1) + 100
t2 = np.zeros(2) + 100
t3 = np.zeros(2) + 100

In [64]:
hat_x, hat_y, hat_C = extend(l1, t1, l2, t2, C12)
print(hat_C)
T = ot.emd(hat_x, hat_y, hat_C)
print(T[:1, :2])

[[100.           1.05263158 100.        ]
 [100.         100.           0.        ]]
[[  0. 255.]]


In [69]:
hat_x, hat_y, hat_C = extend(l2, t2, l3, t3, C23)
print(hat_C)
T = ot.emd(hat_x, hat_y, hat_C)
print(T)

[[  1.11111111 100.         100.        ]
 [100.           1.11111111 100.        ]
 [100.         100.           0.        ]]
[[255.   0.   0.]
 [  0. 255.   0.]
 [  0.   0. 610.]]
